# -*- coding: utf-8 -*-
"""desafio5_Forbes_py_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19o4bHVd9vGXzb7_zzbsGRFwMHneRla2r
"""



"""Desafio 5: Forbes

Definição do problema: Você está trabalhando em um jornal e o editor quer que você responda as seguintes questões:
1. Qual a empresa mais valiosa da lista da Forbes 2000?
2. Construa uma tabela com as TOP10 empresas mais lucrativas da lista.
3. Qual a média de valores de empresa das cinco categorias mais valiosas?

Código do dataset: Forbes2000

DIcas: Método.max()
       Método.nlargest()
       Método.groupby()

"""

from pydataset import data

forbes = data('Forbes2000')

print(forbes.head())

empresa_mais_valiosa = forbes.loc[forbes['marketvalue'].idxmax()]
print("\nEmpresa mais valiosa:")
print(empresa_mais_valiosa)

top_10_lucrativas = forbes.nlargest(10, 'profits')
print("\nTop 10 empresas mais lucrativas:")
print(top_10_lucrativas)

media_valores_categoria = forbes.groupby('category')['marketvalue'].mean().nlargest(5)
print("\nMédia de valores das cinco categorias mais valiosas:")
print(media_valores_categoria)

pip install pydataset